-- Seed data for גמ"ח אייזנבלט (generated from Airtable)
-- 117 members, 201 transactions

begin;
truncate table transactions, members restart identity cascade;

insert into members (airtable_id, code, name, address, phone) values
  ('rec0FZIduLPCAGuX7','2705','ברזל שלמה זלמן','אבי עזרי 30','052-7192705'),
  ('rec0oPbDPinDlskeP','6627','אייזנבלט הורים','','025866627'),
  ('rec2ItcXokTE7GG7u','1535','ורטהימר שמעון','אשר לשלמה 5','050-4191535'),
  ('rec2TOYDZ5c6BVBfz','2114','פרידמן נפתלי מנחם','פונוביז'' 1','052-7132114'),
  ('rec2w8q4Z5swAjM2b','','שמרלר בעריש','',''),
  ('rec4iM5N3pYKkz65j','9098','זלזניק אברהם','יהודה הנשיא 24','052-7669098'),
  ('rec5jPquedUCmolF6','8805','תלפיות','','050-4118805'),
  ('rec5kttOOJj1nioR2','6159','שטרנברג יהושע אשר','חזון איש 9','054-8526159'),
  ('rec5ug9wCjeA04Gah','9467','בירנבוים זלמן','הריטב"א 12 בשביל לנתיבות שלום','054-8439467'),
  ('rec6YUrmmS2CwRkWF','','פודהורצר ילד','עיון התלמוד 5',''),
  ('rec6ZIwb9OKf2LzK1','5482','רבינוביץ ישראל נח','עיון התלמוד 1','052-7665482'),
  ('rec7GtUBW0JcjOKdH','8805','תלפיות פקדון','','050-4118805'),
  ('rec7aOkEXCKpDqwAo','9588','יעקובזון יהודה','עיון התלמוד 3','052-7139588'),
  ('rec88DwdtuA3YKuI5','','אייזנבלט צביקי','',''),
  ('rec89Ee8mm2MwQSjI','','פרידמן אלחנן','אלקבץ 16',''),
  ('rec9Mxa7oF0plC6ge','','פישר נחמן','עיון התלמוד 5',''),
  ('rec9XZbZzFIYIpfkQ','','עשות חסד','ע"י הולצמן',''),
  ('rec9eLV0iVrftHB7I','9267','הרצל שלמה זלמן','עיון התלמוד 5','054-8539267'),
  ('rec9mWLKp45KIt557','8484','פודהורצר משפחת','עיון התלמוד 5','052-7118484'),
  ('recA7uXkWblp2sa72','4162','בוימל שלום צבי','עיון התלמוד 5','050-4134162'),
  ('recA90R14yNJ5bSBG','0048','העשיל אברהם יוסף','עיון התלמוד 5','052-7160048'),
  ('recBQ3yaeRjXxjAJ8','','הולס יהודה יצחק','',''),
  ('recC9U4LTI4VGAGA4','1616','קאליש אברהם דוד','חזון איש 9','052-7151616'),
  ('recCtcKeGHJ8KVFOc','9466','גלאצר מרדכי','זכרון שמואל 2','058-3239466'),
  ('recDyNhIGQyL9fMgw','2672','דרברמדיקר אהרן','חזון איש 5','054-8432672'),
  ('recEJroWCNYaVPmk2','7266','שולמן אשר מאיר','זכרון שמואל 4','052-7127266'),
  ('recEOO6Ah90EztbSS','8949','אייזנשטין יצחק','קרית ספר','054-8438949'),
  ('recEap5rtjW38POrt','3209','בוימל מרדכי יהודה','חזון איש 9','054-8493209'),
  ('recEf0c8u9iCU1Olb','0664','פרידמן משפחת','אלקבץ 16/29 י-ם','0 2-5800664'),
  ('recF9ZVgQeTSZ8kxW','7146','ציינווירט יצחק','עיון התלמוד 1','054-8457146'),
  ('recFIRK7VbNI74R7d','6263','דייטש משה ישראל','חזון איש 7','054-8426263'),
  ('recGSaf61E1GawOTA','4557','ברוכשטט פנחס','עיון התלמוד 1','050-4174557'),
  ('recH4ireGUZR8EWZU','8401','ציינווירט משה נתן דוב','חזון איש 5','052-7638401'),
  ('recHeXAwqro8hMNqB','1953','שטרנברג זוסיא חיים','אשר לשלמה 3','052-7111953'),
  ('recHhnIClU3AgbNO4','4055','ברזל חיים ישראל','פונוביז'' 3','052-7154055'),
  ('recIGkzM9U9FIot6U','1385','ויסברג אברהם','אשר לשלמה 3','052-7601385'),
  ('recITJIY3kLLXPPHe','','שפרינגער איטשע','',''),
  ('recJ9PFKK2pEDEPmU','0651','ורטהימר בן ציון','חזון איש 18','052-7180651'),
  ('recJW4v31vwFCK6Wj','1234','אייזנבלט בן ציון','','1234'),
  ('recJWRFakfeggq8an','1645','שמרלר אברהם בנימין','עיון התלמוד 5','058-3221645'),
  ('recK3yJYs2fU9VLFd','9762','רבינוביץ אברהם מנחם מנדל','פונוביז'' 1','052-7179762'),
  ('recKAB1TS0bdOTpMs','2139','ורטהימר יעקב מנחם','אבי עזרי 30','054-8532139'),
  ('recKXvTWDo7Y7SAIm','5765','הרב דאוויד יעקב צבי','חזון דוד','052-7185765'),
  ('recLIM6jwUU0AfxXt','','וויס ר'' אפרים','סנהדריה ירושלים',''),
  ('recLMKSwrNHLG3oeh','0664','פרידמן חומש','אלקבץ 16/29 י-ם','0 2-5800664'),
  ('recLTEJQ6PEF9C9XC','4330','שינברגר עקיבא','פונוביז'' 5','052-7154330'),
  ('recMU2jO5CXNxe437','9580','הפטלר אברהם חיים','עיון התלמוד 1','058-3239580'),
  ('recMgOMREMChopA7B','4358','אייזנבלט ביתר','חבד 16','02-5804358'),
  ('recNn7xwOMnmokY54','6058','רוזן משפחת','בן איש חי בי"ש','054-8426058'),
  ('recPq1IwK2ywCU0fQ','','פודהוצר הכנסת כלה','',''),
  ('recQf8WKbbYfuE7eq','4136','רבינוביץ מרדכי שלמה','עיון התלמוד 1','052-7144136'),
  ('recRDomaWMgJo6hJI','0643','שטרנברג אהרן נחמן','חזון איש 5','052-7610643'),
  ('recRuiu00Cq8Uh6X9','1315','ויסברג שלמה','עמנואל','025-7101315'),
  ('recSRSrsFsoHjyzhy','0967','הולס משה','חזון איש 9','052-7670967'),
  ('recT1hMtUeglthMT5','0373','גרומן טוביה פנחס','ירושלים','053-3110373'),
  ('recTSSpxTwO1tcmRd','4791','דרברמדיקר ירחמיאל משה','אבי עזרי 34','052-7654791'),
  ('recUAwRmHQby70WVj','0610','שובקס יעקב ישראל','פונוביז'' 1','052-7140610'),
  ('recUHMcyJhQZa8zqy','2385','שטרנברג אליהו יהודה','עיון התלמוד 5','050-4132385'),
  ('recUdMnKsadW6FLPq','2173','שטרנברג ברוך יצחק יהודה','אשר לשלמה 1','052-7112173'),
  ('recV64YBNV031gnOL','8850','פריינד חיים שלום','אשר לשלמה 1','050-4118850'),
  ('recVAwftBOISbQleA','','אייזנבלט אברומי','בית שמש',''),
  ('recVQpb8LRarmrqBL','','רוזנבלט פריידי','סנהדריה ירושלים',''),
  ('recVexTf6B8nXOmTi','7604','פרידמן חיים יעקב','חזון איש 9','052-7697604'),
  ('recVodw3ZEvH7NYp2','','הולצמן יוסף','',''),
  ('recWdA6IpBkwlTBr5','3474','רבינוביץ משה צבי','פונוביז'' 6','05331-03474'),
  ('recWuECMOq5wcMHkq','3456','ברנשטיין דוד זעליג','אבי עזרי 34','050-4173456'),
  ('recXLZcGbz3axATB4','6699','','','6699'),
  ('recXYmAOy3POxVvYh','8067','קופשיץ צבי','ב"ר שמואל','052-7638067'),
  ('recY2RMF9NT4vlyeW','8204','הרשלר ישראל','אבי עזרי 34','05484-98204'),
  ('recYjR3AofQs2O5rI','0143','גפנר פינחס','עיון התלמוד 1','052-7140143'),
  ('recbgHCczE3Ly7lLJ','2782','פריינד ישראל יוסף','עיון התלמוד 3','054-8422782'),
  ('recc449jB8H0RhAu5','6479','קליין שלמה צבי','פונוביז'' 3','052-7116479'),
  ('reccC4BQ2hhUfZyjw','3731','שיינפלד יהושע','נהר הירדן','054-8403731'),
  ('reccKiP1MSn7i1Yg9','3691','גוטפריד אפרים פישל','פונוביז'' 5','050-4193691'),
  ('reccyyOlxo1iCxLzM','6810','רבינוביץ מרדכי שלמה','פונוביז'' 5','053-3186810'),
  ('recdA6JZc8IW4ahDV','','צביקי קופה','',''),
  ('recfxmravjg6VaSBX','9555','ברזל משה זאב','חזון איש 7','053-3169555'),
  ('recgKRqfrWcqvSNRx','3080','ברנשטיין ירמיהו ליב','נתיבות שלום 13','053-3133080'),
  ('reci7V3sIp5HeHvfb','0028','שובקס מרדכי שלמה','אשר לשלמה 3','052-7650028'),
  ('recjbgGhGdrg5j1H4','7508','ברנשטיין יעקב ישראל','אבי עזרי 10 אצל שפרינצלס','050-4167508'),
  ('recklTOfb0r13IO9g','','קרן הבנין- קלויז מ"ע','',''),
  ('reckyzCC5qOpm5oze','1498','וינשטוק משה יאיר','אשר לשלמה 3','052-7161498'),
  ('recl9anBucXRYafGT','4576','בירנבוים אברהם יעקב','פונוביז'' 1','052-7164576'),
  ('reclFyzgRhbzgwzgN','7965','הולצמן שלמה זלמן','עיון התלמוד 5','05484-47965'),
  ('reclRPYov4M3uqNrS','8210','רבינוביץ מרדכי ליבר','חזון איש 9','052-7118210'),
  ('recldvpHDLDm9Kme1','5618','רבינוביץ שלום','אשר לשלמה 1','052-7155618'),
  ('reclqBXAgREdFjxAb','3960','רבינוביץ מש ברי','ביתר','053-3103960'),
  ('reclvAYjYjQeE2TBo','3766','שמרלר יצחק','אשר לשלמה 3','052-7693766'),
  ('recmIAG61KsePS7bC','0991','רבינוביץ אברהם יעקב','פונוביז'' 3','052-7160991'),
  ('recmOrkiaXSM3IHiS','','ברזל אברהם ישעיהו','אבני נזר 12',''),
  ('recn0wjo9iw0m4m5s','6992','ויסברג יוסף דוד','חזון איש 9','053-3106992'),
  ('recn2Cg6DjGz6G3XC','3654','אינגבר מרדכי שלמה','חזון איש 9','054-8403654'),
  ('recnEWOXmPUFr7Ter','','טאטי השקעה לוד','',''),
  ('recnVpGB9Qb7jqlFU','','פודהוצר ד.','עיון התלמוד 5',''),
  ('recoBbWUIHD53JcNy','7884','כץ יהודה','','053-3147884'),
  ('recocTpOErsz4bebc','6057','רויטנברג משפחת','','548426057'),
  ('recovuiBnk7lc4iMt','','שפירא חיים','',''),
  ('recp866WaOeZrRAL8','5655','רבינוביץ מאיר שלום','אשר לשלמה 1','0533-145655'),
  ('recpG9jZ35Oj4M4U0','5754','ברנשטיין משה טוביה','עיון התלמוד 3','05331-45754'),
  ('recpHY28ahVyI4D6c','0797','וובר ישראל מרדכי','עיון התלמוד 1','05484-60797'),
  ('recpaL5EjZjOd66ai','','עמותה רבינוביץ','',''),
  ('recpfc3eNTSmJlQbx','7046','פישמן נפתלי','עיון התלמוד 5','052-7687046'),
  ('recqaDHp9N9xYbUjr','','גולדיהרש דוד','',''),
  ('recr4e20hIPID88Av','','גמח ביתר','',''),
  ('recre1Z7gaYE1aEAR','2915','ורטהימר משה','','050-4122915'),
  ('recsIMBaUVWIF61vk','3456','משה טסט','','0527123456'),
  ('recsIya3vDYHfme3K','0100','גראף יוסף חיים','חזון איש 5','050-4100100'),
  ('recuNCa8gWJ9KGsqH','1188','ברזל נתן נטע','פונוביז'' 5','052-7631188'),
  ('recv12v6X5aTOo26M','','גודלבסקי יעקב','',''),
  ('recvHixGczMKZge3q','7307','רוזן אשר מאיר','עיון התלמוד 3','054-8457307'),
  ('recwsXkbjHGDvKbYT','8067','קופשיץ זלמן','ב"ר שמואל','052-7638067'),
  ('recx2EjzFJDWy2YnY','','רוזנבלט שלמה','סנהדריה ירושלים',''),
  ('recxLw6vRFuNL7PH3','7623','גפנר שמעון מנחם מנדל ראובן','עיון התלמוד 5','054-8467623'),
  ('recyKmV3zLBYmylZu','9512','פישמן מרדכי שלמה','עיון התלמוד 1','052-7619512'),
  ('recyMI749evVotJ9a','','אייזנבלט כתבים','',''),
  ('recyQwYTLflZfB1Kh','5688','אייזנבלט שלומי','בני ברק','053-4125688'),
  ('reczkGKTu4sILMYZ9','8067','קופשיץ שמואל הלל','חזון איש 3','052-7638067');

insert into transactions (member_id, amount, type, method, greg_date, heb_date, notes)
select m.id, t.amount, t.type, t.method, t.greg_date, t.heb_date, t.notes
from (values
  ('rec0oPbDPinDlskeP', 371::numeric, 'משיכה', null, null::date, 'ו אייר פג', 'ויטמינים רוזן'),
  ('recJW4v31vwFCK6Wj', 800::numeric, 'הפקדה', null, null::date, null, null),
  ('rec0oPbDPinDlskeP', 588::numeric, 'משיכה', null, null::date, 'חשון פג', 'אימייל 2021'),
  ('rec0oPbDPinDlskeP', 1500::numeric, 'משיכה', null, null::date, 'כט טבת', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 22000::numeric, 'משיכה', null, null::date, 'כא אדר פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 740::numeric, 'משיכה', null, null::date, 'ט כסליו פה', 'הסעות להרשל'),
  ('rec0oPbDPinDlskeP', 100000::numeric, 'הפקדה', null, null::date, 'חשון פד', 'אשראי גולדיהרש לחזקי לב'),
  ('rec0oPbDPinDlskeP', 33000::numeric, 'משיכה', null, null::date, 'ו אדר פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 37000::numeric, 'משיכה', null, null::date, 'יט אדר פג', 'הלוואה לישראל'),
  ('rec0oPbDPinDlskeP', 14000::numeric, 'הפקדה', null, null::date, 'ד ניסן פו', 'העברה לפריזנט'),
  ('rec0oPbDPinDlskeP', 26000::numeric, 'משיכה', null, null::date, 'טבת פה', 'חתונה רוזנבלט'),
  ('rec0oPbDPinDlskeP', 36500::numeric, 'הפקדה', null, null::date, 'יא אדר פה', 'חוב טאטי מישראל לשיינפלד'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'כו אייר פא', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'הפקדה', null, null::date, 'ז אלול פה', 'מבוקשפן עו"ד'),
  ('rec0oPbDPinDlskeP', 40800::numeric, 'משיכה', null, null::date, 'יא חשון פה', 'לקארפ ירושה'),
  ('rec0oPbDPinDlskeP', 3060::numeric, 'משיכה', null, null::date, 'אלול פא', 'הודו אב'),
  ('rec0oPbDPinDlskeP', 400::numeric, 'משיכה', null, null::date, 'יד תמוז פג', 'נטע- חשבונות ירושה'),
  ('rec0oPbDPinDlskeP', 2070::numeric, 'משיכה', null, null::date, 'א אדא', 'משנ"י'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'הפקדה', null, null::date, '29.11.23', 'מחסדי רבקה'),
  ('rec0oPbDPinDlskeP', 1236::numeric, 'משיכה', null, null::date, 'ט ניסן פה', '0'),
  ('rec0oPbDPinDlskeP', 500::numeric, 'הפקדה', null, null::date, 'ה אייר פג', 'מאבי יפה'),
  ('rec0oPbDPinDlskeP', 0::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'סיכום ירושה באבי'),
  ('rec0oPbDPinDlskeP', 100000::numeric, 'הפקדה', null, null::date, 'ט אלול', 'דולרים בבנק'),
  ('rec0oPbDPinDlskeP', 20930::numeric, 'משיכה', null, null::date, 'חשון פג', 'הודו אד"ב פב-תשרי פג'),
  ('rec0oPbDPinDlskeP', 4800::numeric, 'משיכה', null, null::date, 'שבט פו', 'לרותי לדירה'),
  ('rec0oPbDPinDlskeP', 1929::numeric, 'משיכה', null, null::date, 'יט כסליו פב', 'משנ"י חשון-כסליו'),
  ('rec0oPbDPinDlskeP', 700::numeric, 'הפקדה', null, null::date, 'ה תמוז פד', 'מזומן מעטפה'),
  ('rec0oPbDPinDlskeP', 1400000::numeric, 'הפקדה', null, null::date, 'ז שבט פו', 'תשלום דורלכר'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'הפקדה', null, null::date, 'א אדר פו', 'למוטי פריזנט'),
  ('rec0oPbDPinDlskeP', 6000::numeric, 'משיכה', null, null::date, 'ז שבט פו', 'העברה לחשבונם'),
  ('rec0oPbDPinDlskeP', 70000::numeric, 'הפקדה', null, null::date, 'ח אלול פה', 'לשיינפלד'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'הפקדה', null, null::date, 'כה אב פא', 'הפקדה'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'הפקדה', null, null::date, 'יא ניסן פו', 'העברה פרקש'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'משיכה', null, null::date, 'ב ניסן פד', 'מזומן למצות'),
  ('rec0oPbDPinDlskeP', 1600::numeric, 'משיכה', null, null::date, 'כט אד"א', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 605::numeric, 'משיכה', null, null::date, 'כח כסליו', 'לרוזן ויטמינים'),
  ('recJW4v31vwFCK6Wj', 150::numeric, 'משיכה', null, null::date, 'אב', null),
  ('rec0oPbDPinDlskeP', 16000::numeric, 'הפקדה', null, null::date, 'יא כסליו פג', 'שקים'),
  ('rec0oPbDPinDlskeP', 150::numeric, 'משיכה', null, null::date, 'ד תשרי פד', 'הסעה לדיון הרשל'),
  ('rec0oPbDPinDlskeP', 1400::numeric, 'משיכה', null, null::date, 'כ כסליו פד', 'לרופא והסעה הרשל'),
  ('rec0oPbDPinDlskeP', 1350::numeric, 'משיכה', null, null::date, 'ח ניסן פה', 'למאפיה מצות'),
  ('rec0oPbDPinDlskeP', 618::numeric, 'משיכה', null, null::date, 'כ טבת פג', 'לפרידמן למזוזות'),
  ('rec0oPbDPinDlskeP', 13000::numeric, 'משיכה', null, null::date, 'יז שבט פג', 'הלוואה לישראל'),
  ('rec0oPbDPinDlskeP', 14700::numeric, 'הפקדה', null, null::date, 'א שבט פו', 'העברה'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'הפקדה', null, null::date, 'כו אדר פו', 'העברה לפריזנט'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'א סיון', 'פרסומת לסידור'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'משיכה', null, null::date, 'כט אב פה', '0'),
  ('rec0oPbDPinDlskeP', 80::numeric, 'משיכה', null, null::date, 'סיון פג', 'כריכות לסידורים באבי'),
  ('rec0oPbDPinDlskeP', 560::numeric, 'משיכה', null, null::date, 'ד אלול', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 4250::numeric, 'משיכה', null, null::date, 'א אב פד', 'לעו"ד שמעון מאיר'),
  ('rec0oPbDPinDlskeP', 122500::numeric, 'הפקדה', null, null::date, 'יב חשון פה', 'החזר מדירה ביתר'),
  ('rec0oPbDPinDlskeP', 2300::numeric, 'משיכה', null, null::date, 'כט אדר פג', 'לפאה יוכבד'),
  ('rec0oPbDPinDlskeP', 500::numeric, 'משיכה', null, null::date, 'כז ניסן', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 30000::numeric, 'משיכה', null, null::date, 'ה ניסן פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 230::numeric, 'משיכה', null, null::date, 'כב אייר', 'לישראל מצות'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'ל חשוון פב', 'לוויטמינים'),
  ('rec0oPbDPinDlskeP', 1512::numeric, 'הפקדה', null, null::date, 'ט אלול', 'דולרים בבנק'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'כד שבט פו', 'תרומה לשלומי'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'משיכה', null, null::date, 'יט תמוז פא', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 15740::numeric, 'משיכה', null, null::date, '0', 'הודו אייר פג-אדב פד'),
  ('rec0oPbDPinDlskeP', 1800::numeric, 'הפקדה', null, null::date, 'ו ניסן פו', 'למצות'),
  ('rec0oPbDPinDlskeP', 20400::numeric, 'משיכה', null, null::date, 'כד חשון פה', 'לגודלבסקי לירושה'),
  ('rec0oPbDPinDlskeP', 882::numeric, 'משיכה', null, null::date, 'מ07/23 עד סוף 24', 'קול הלשון להרשל'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'הפקדה', null, null::date, '45813', 'מרוזן שקים 1000 לחודש יגמור בהנ"ל'),
  ('rec0oPbDPinDlskeP', 1090::numeric, 'משיכה', null, null::date, 'כא אדר פו', 'לפרידמן'),
  ('rec0oPbDPinDlskeP', 11468::numeric, 'משיכה', null, null::date, '0', 'הודו ניסן- אלול פד'),
  ('rec0oPbDPinDlskeP', 525::numeric, 'משיכה', null, null::date, 'חשון פג', 'פאלפון 2021'),
  ('rec0oPbDPinDlskeP', 250::numeric, 'משיכה', null, null::date, 'ז ניסן פג', 'מחזורים דסי'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'משיכה', null, null::date, 'כב אדא', 'העברה לסילבר'),
  ('rec0oPbDPinDlskeP', 110000::numeric, 'הפקדה', null, null::date, 'ז שבט פג', 'העברה לחשבוני מפרידמן'),
  ('rec0oPbDPinDlskeP', 441::numeric, 'משיכה', null, null::date, 'חשון פג', 'אימייל עד 09/22'),
  ('rec0oPbDPinDlskeP', 95000::numeric, 'משיכה', null, null::date, 'כסליו  פו', 'תיווך'),
  ('rec0oPbDPinDlskeP', 2444::numeric, 'משיכה', null, null::date, 'יט תמוז פא', 'משנת יוסף לחודשיים'),
  ('rec0oPbDPinDlskeP', 2860::numeric, 'משיכה', null, null::date, 'אב פא', 'הודו תמוז'),
  ('rec0oPbDPinDlskeP', 6500::numeric, 'הפקדה', null, null::date, 'ה אדר פה', 'מישראל'),
  ('recsIMBaUVWIF61vk', 5000::numeric, 'משיכה', 'צ''יקים', '2026-04-28'::date, null, null),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'כט תמוז פד', 'העברה לעלי שיח'),
  ('rec0oPbDPinDlskeP', 700::numeric, 'משיכה', null, null::date, 'ו אלול פג', 'לרותי לחשבונות'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'הפקדה', null, null::date, 'אייר פא', 'קיבלתי מרוזנבלט'),
  ('rec0oPbDPinDlskeP', 200::numeric, 'משיכה', null, null::date, 'יג תשרי פו', 'לפרידמן'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'ניסן פד', 'העברה לחשבון הוצאות לוד'),
  ('rec0oPbDPinDlskeP', 2100::numeric, 'משיכה', null, null::date, 'אלול פב', 'פאה צירי'),
  ('rec0oPbDPinDlskeP', 2207::numeric, 'משיכה', null, null::date, 'י תמוז', 'הודו סיון'),
  ('rec0oPbDPinDlskeP', 110000::numeric, 'הפקדה', null, null::date, 'ב שבט פג', 'הפקדה בחשבוני מפרידמן'),
  ('rec0oPbDPinDlskeP', 3900::numeric, 'הפקדה', null, null::date, 'יא תשרי פב', 'שיקים ישראל אייר-כסליו פב'),
  ('rec0oPbDPinDlskeP', 30200::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 3800::numeric, 'משיכה', null, null::date, 'כח אדר פו', 'לנגר'),
  ('rec0oPbDPinDlskeP', 3550::numeric, 'משיכה', null, null::date, 'ניסן פד', 'הוצאות מצות'),
  ('rec0oPbDPinDlskeP', 1700::numeric, 'משיכה', null, null::date, 'כג אדב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'י שבט פג', 'רוזן ויטמינים'),
  ('rec0oPbDPinDlskeP', 350::numeric, 'משיכה', null, null::date, 'כו ניסן פו', 'לכנס חינוך'),
  ('rec0oPbDPinDlskeP', 4475::numeric, 'משיכה', null, null::date, 'ו אדר פו', 'לשיינפלד חתונה'),
  ('rec0oPbDPinDlskeP', 17000::numeric, 'משיכה', null, null::date, 'ו אדר פו', 'לקרמיקה'),
  ('rec0oPbDPinDlskeP', 15000::numeric, 'הפקדה', null, null::date, 'טז שבט פו', 'בהעברה לפריזנט'),
  ('rec0oPbDPinDlskeP', 700::numeric, 'הפקדה', null, null::date, 'ד תמוז פד', 'מעטפה מזומן'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'אדר פה', 'עמלה כסף לאברהם שמואל'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'הפקדה', null, null::date, 'ז תמוז פא', 'שיק'),
  ('rec0oPbDPinDlskeP', 1800::numeric, 'משיכה', null, null::date, 'ניסן פג', 'פאה צירי'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'הפקדה', null, null::date, 'כה טבת פד', 'מזומן'),
  ('rec0oPbDPinDlskeP', 6700::numeric, 'הפקדה', null, null::date, 'כ כסליו פג', 'הכניסו לי לפרידמן'),
  ('rec0oPbDPinDlskeP', 362::numeric, 'משיכה', null, null::date, 'ו אייר פג', 'לקול הדף'),
  ('rec0oPbDPinDlskeP', 400::numeric, 'משיכה', null, null::date, 'י כסליו פו', 'הסעות הרשל'),
  ('rec0oPbDPinDlskeP', 280::numeric, 'הפקדה', null, null::date, 'א שבט', 'מטופל טאטי'),
  ('rec0oPbDPinDlskeP', 22220::numeric, 'הפקדה', null, null::date, 'כט אלול פג', 'הפקדה להלוואה לשפרינגער'),
  ('rec0oPbDPinDlskeP', 66125::numeric, 'הפקדה', null, null::date, 'אייר פד', 'מגולדיהרש דרך אבי יפה'),
  ('rec0oPbDPinDlskeP', 3382::numeric, 'משיכה', null, null::date, 'חשון פב', 'הודו תשרי'),
  ('rec0oPbDPinDlskeP', 64::numeric, 'משיכה', null, null::date, 'ד תשרי פד', 'קניה תבלינים'),
  ('rec0oPbDPinDlskeP', 110::numeric, 'הפקדה', null, null::date, 'שבט פד', 'מכירת סידורים'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'ט שבט פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 3000::numeric, 'משיכה', null, null::date, 'כח אדר פו', 'לריצוף'),
  ('rec0oPbDPinDlskeP', 9000::numeric, 'הפקדה', null, null::date, 'עד טבת פב', 'החזר חודשי מכהן'),
  ('rec0oPbDPinDlskeP', 41::numeric, 'משיכה', null, null::date, 'ל אדא פד', 'מונית להרשל'),
  ('rec0oPbDPinDlskeP', 1420::numeric, 'משיכה', null, null::date, 'יז אב פא', 'לרוזן-שפרינגער'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'יח אדא פד', 'ליעקב גודלבסקי-ירושה'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'ג אב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 250000::numeric, 'הפקדה', null, null::date, 'אב פה', 'שקים הפקדתי לרוזנבלט'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'יב חשון פו', 'לצביקי'),
  ('rec0oPbDPinDlskeP', 300::numeric, 'משיכה', null, null::date, 'ח חשון פג', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 100000::numeric, 'הפקדה', null, null::date, 'סיון פד', 'העברה מאמריקה דרך אבי יפה'),
  ('rec0oPbDPinDlskeP', 8000::numeric, 'הפקדה', null, null::date, 'אייר פא', 'שיקים ישראל אייר-כסליו פב'),
  ('rec0oPbDPinDlskeP', 2118::numeric, 'משיכה', null, null::date, 'ד ניסן פו', 'לשיינפלד חתונה'),
  ('recJW4v31vwFCK6Wj', 200::numeric, 'משיכה', null, null::date, 'כז אלול פד', null),
  ('rec0oPbDPinDlskeP', 3965::numeric, 'משיכה', null, null::date, 'כט אב פא', 'לרוזן-שפרינגער'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'כד סיון', 'לרוזן ויטמינים'),
  ('rec0oPbDPinDlskeP', 150::numeric, 'משיכה', null, null::date, 'טו אב פה', 'להרשל'),
  ('rec0oPbDPinDlskeP', 6000::numeric, 'משיכה', null, null::date, 'ח תשרי פה', 'חתונה רוזנבלט'),
  ('rec0oPbDPinDlskeP', 3000::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לאשר ניסן'),
  ('rec0oPbDPinDlskeP', 53000::numeric, 'הפקדה', null, null::date, 'א כסליו פד', 'אשראי גולדיהרש לשיינפלד'),
  ('recsIMBaUVWIF61vk', 6500::numeric, 'הפקדה', 'מזומן', null::date, null, null),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'ל שבט פו', 'לנגר'),
  ('rec0oPbDPinDlskeP', 53710::numeric, 'הפקדה', null, null::date, '28.11.23', 'מחסדי רבקה'),
  ('rec0oPbDPinDlskeP', 500::numeric, 'משיכה', null, null::date, 'כט אייר פד', 'ליצחק שכטר'),
  ('rec0oPbDPinDlskeP', 432::numeric, 'משיכה', null, null::date, 'יא כסליו פג', 'ויטמינים רוזן'),
  ('rec0oPbDPinDlskeP', 645::numeric, 'משיכה', null, null::date, 'חשון פג', 'פאלפון 2022'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'יז טבת פו', 'דירה'),
  ('rec0oPbDPinDlskeP', 1030::numeric, 'משיכה', null, null::date, 'כו אדב פד', 'לקארפ'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'משיכה', null, null::date, 'יא אייר פד', 'לשרוליק'),
  ('rec0oPbDPinDlskeP', 30000::numeric, 'משיכה', null, null::date, 'יג סיון פד', 'לסוכן סידורים'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'הפקדה', null, null::date, 'ב אלול פא', 'שיק ומזומן'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'ו תשרי פב', 'העברה'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'ג שבט פג', 'לעו"ד של הרשל'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'ט שבט פו', 'אלי לבניה'),
  ('rec0oPbDPinDlskeP', 240000::numeric, 'משיכה', null, null::date, 'כסליו פו', 'משיינפלד'),
  ('rec0oPbDPinDlskeP', 960::numeric, 'משיכה', null, null::date, 'ב תמוז', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 2700::numeric, 'משיכה', null, null::date, 'יא אייר פד', 'מחשבון גולדיהרש עבור רבינוביץ מביתר'),
  ('rec0oPbDPinDlskeP', 1600::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לבנצי ורטהימר'),
  ('rec0oPbDPinDlskeP', 25000::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'סיכום לוד'),
  ('rec0oPbDPinDlskeP', 83::numeric, 'משיכה', null, null::date, 'ג אב פא', 'לטלזטון'),
  ('rec0oPbDPinDlskeP', 800::numeric, 'משיכה', null, null::date, 'כד חשון פב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'י אלול פד', 'הלוואה לשושן'),
  ('rec0oPbDPinDlskeP', 12294::numeric, 'משיכה', null, null::date, 'אייר פג', 'הודו חשון- ניסן פג'),
  ('rec0oPbDPinDlskeP', 1483::numeric, 'משיכה', null, null::date, 'א סיון פא', 'הודו אייר'),
  ('rec0oPbDPinDlskeP', 360::numeric, 'משיכה', null, null::date, 'טו חשון פו', 'לרוזנבלט בגדים'),
  ('rec0oPbDPinDlskeP', 400::numeric, 'משיכה', null, null::date, 'יז אדא', 'לשלזינגר'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'משיכה', null, null::date, 'חורף פד', 'לרותי לחשבונות'),
  ('rec0oPbDPinDlskeP', 5000::numeric, 'הפקדה', null, null::date, 'כ שבט פו', 'אלי'),
  ('rec0oPbDPinDlskeP', 2137::numeric, 'משיכה', null, null::date, 'יא תשרי פב', 'סיכום משנת יוסף'),
  ('rec0oPbDPinDlskeP', 11000::numeric, 'הפקדה', null, null::date, 'כא אדר פו', 'העברה'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'יא אייר פה', 'לפרידמן חלאקה'),
  ('rec0oPbDPinDlskeP', 1800::numeric, 'משיכה', null, null::date, 'טז סיון פא', 'עוזרי'),
  ('rec0oPbDPinDlskeP', 3755::numeric, 'משיכה', null, null::date, 'טו אייר פא', 'משנת יוסף'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'משיכה', null, null::date, 'כח אדר פו', 'לנגר'),
  ('rec0oPbDPinDlskeP', 110000::numeric, 'הפקדה', null, null::date, 'סיון פא', 'מ10/06/21 1000 החזר לחודש'),
  ('rec0oPbDPinDlskeP', 250::numeric, 'משיכה', null, null::date, 'יח תמוז פד', 'בי"מ להרשל'),
  ('rec0oPbDPinDlskeP', 1100::numeric, 'משיכה', null, null::date, 'יז אייר פא', 'עוזרי'),
  ('rec0oPbDPinDlskeP', 30000::numeric, 'משיכה', null, null::date, 'אדר פה', 'לאברהם שמואל'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'הפקדה', null, null::date, 'כ כסליו פו', 'העברה'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'משיכה', null, null::date, 'כט אב פד', 'לרוזנבלט חתונה'),
  ('rec0oPbDPinDlskeP', 35000::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 255::numeric, 'משיכה', null, null::date, 'כג אייר', 'לשפרינגער'),
  ('rec0oPbDPinDlskeP', 5100::numeric, 'משיכה', null, null::date, 'ל ניסן פד', 'לרוזנבלט לתנאים'),
  ('rec0oPbDPinDlskeP', 360::numeric, 'משיכה', null, null::date, 'כד תשרי פג', 'סידורים'),
  ('rec0oPbDPinDlskeP', 2600::numeric, 'משיכה', null, null::date, 'ט שבט פו', 'לבנצי ורטהימר'),
  ('rec0oPbDPinDlskeP', 80000::numeric, 'הפקדה', null, null::date, 'כ שבט פו', 'לאינגבר'),
  ('rec0oPbDPinDlskeP', 51500::numeric, 'משיכה', null, null::date, 'כה אב פד', 'לקארפ מירושה'),
  ('rec0oPbDPinDlskeP', 10530::numeric, 'משיכה', null, null::date, 'אייר פג', 'עו"ד לישראל'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'סיכום בונדס'),
  ('rec0oPbDPinDlskeP', 437::numeric, 'משיכה', null, null::date, 'ד ניסן פו', 'לפאלפון הרשל 2025'),
  ('rec0oPbDPinDlskeP', 34500::numeric, 'הפקדה', null, null::date, 'עדין לא קיבלתי', 'החזרים מרוזן להלוואה'),
  ('rec0oPbDPinDlskeP', 250::numeric, 'הפקדה', null, null::date, 'יא תמוז פא', 'שיק'),
  ('rec0oPbDPinDlskeP', 1200::numeric, 'משיכה', null, null::date, 'יח שבט פד', 'לרופא והסעה הרשל'),
  ('rec0oPbDPinDlskeP', 1200::numeric, 'משיכה', null, null::date, 'כח אב פד', 'פאלפון והמבשר להרשל עד סוף 2024'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'כח שבט', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 73000::numeric, 'משיכה', null, null::date, 'כסליו  פו', 'תיווך'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'כ אדא פד', 'ליעקב גודלבסקי-ירושה'),
  ('rec0oPbDPinDlskeP', 26200::numeric, 'משיכה', null, null::date, 'כסליו  פו', 'עו"ד בוקשפן'),
  ('rec0oPbDPinDlskeP', 7000::numeric, 'משיכה', null, null::date, 'ו אייר פד', 'מחשבון גולדיהרש עבור רבינוביץ מביתר'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'הפקדה', null, null::date, 'ה כסליו פד', 'שק להוצאות של הרשל'),
  ('rec0oPbDPinDlskeP', 30800::numeric, 'משיכה', null, null::date, 'ב שבט פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'ד תשרי פג', 'ויטמינים רוזן'),
  ('rec0oPbDPinDlskeP', 8650::numeric, 'משיכה', null, null::date, 'יב אייר פד', 'רוזנבלט הוצאות חתונה'),
  ('rec0oPbDPinDlskeP', 3915::numeric, 'משיכה', null, null::date, 'תשרי פב', 'הודו אלול'),
  ('rec0oPbDPinDlskeP', 65::numeric, 'משיכה', null, null::date, 'יג אלול פד', 'קיטל'),
  ('rec0oPbDPinDlskeP', 3000::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לרותי לדירה'),
  ('rec0oPbDPinDlskeP', 1150::numeric, 'משיכה', null, null::date, 'יח אב פא', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'יט אלול פד', 'הסעה הרשל לשרייכר'),
  ('rec0oPbDPinDlskeP', 3339::numeric, 'הפקדה', null, null::date, 'יד אייר פא', 'סיכום'),
  ('rec0oPbDPinDlskeP', 18300::numeric, 'משיכה', null, null::date, 'ניסן פד', '5000$ של האייער'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'משיכה', null, null::date, 'כה תשרי פב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 15000::numeric, 'משיכה', null, null::date, 'כו חשון פה', 'לרוזנבלט חתונה'),
  ('rec0oPbDPinDlskeP', 645::numeric, 'משיכה', null, null::date, 'ב אייר פג', 'ישראל לגרושה')
) as t(member_aid, amount, type, method, greg_date, heb_date, notes)
join members m on m.airtable_id = t.member_aid;

commit;
